### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ricardobarroslourenco** [conda-forge/cartopy_offlinedata-feedstock#16]
### Comment:

Hi! I'm an HPC user, and I intend to use cartopy with this offline base. 

How does it works? I am failing to find documentation on this.

**Comment by xylar** [comment]
@ricardobarroslourenco, you're right, unfortunately there isn't a good place to document this.

You just install the conda package, which includes the data that cartopy would otherwise download on demand. An environment variable `$CARTOPY_DATA_DIR` is set when the conda environment gets activated (so don't use the base environment, since I don't think the activation script gets called there) that point cartopy to the data.

**Comment by ricardobarroslourenco** [comment]
Thanks. That explains a lot :)
